"""Package services."""

from .doctor import Check, DoctorReport, Fix, FixKind, collect_checks, uses_vm
from .guide_service import guide_url
from .lab_service import (
    CheckResult,
    ScoreResult,
    check_lab,
    clean_lab,
    compute_score,
    evaluate_lab,
    find_lab,
    get_all_labs,
    get_lab,
    lab_session_spec,
    lab_status,
    open_lab_session,
    reset_lab,
    resolve_pytest_cmd,
    run_lab,
    stop_lab,
    validate_all_metadata,
    validate_all_structure,
)
from .progress_service import (
    BlocProgress,
    build_progress,
    next_pending_lab,
    pedagogical_sort_key,
)

__all__ = [
    "BlocProgress",
    "Check",
    "CheckResult",
    "DoctorReport",
    "Fix",
    "FixKind",
    "ScoreResult",
    "build_progress",
    "check_lab",
    "clean_lab",
    "collect_checks",
    "compute_score",
    "evaluate_lab",
    "find_lab",
    "get_all_labs",
    "get_lab",
    "guide_url",
    "lab_session_spec",
    "lab_status",
    "next_pending_lab",
    "open_lab_session",
    "pedagogical_sort_key",
    "reset_lab",
    "resolve_pytest_cmd",
    "run_lab",
    "stop_lab",
    "uses_vm",
    "validate_all_metadata",
    "validate_all_structure",
]
