"""Package reporting."""

from .console import (
    console,
    err_console,
    error,
    info,
    print_check_result,
    print_course_end,
    print_course_list,
    print_course_section,
    print_course_toc,
    print_doctor,
    print_fullhelp,
    print_hint,
    print_lab_challenge,
    print_lab_course,
    print_lab_detail,
    print_lab_welcome,
    print_labs_table,
    print_progress_table,
    print_scores_table,
    print_structure_reports,
    success,
    warn,
)

__all__ = [
    "console",
    "err_console",
    "error",
    "info",
    "print_check_result",
    "print_course_end",
    "print_course_list",
    "print_course_section",
    "print_course_toc",
    "print_doctor",
    "print_fullhelp",
    "print_hint",
    "print_lab_challenge",
    "print_lab_course",
    "print_lab_detail",
    "print_lab_welcome",
    "print_labs_table",
    "print_progress_table",
    "print_scores_table",
    "print_structure_reports",
    "success",
    "warn",
]
